---
title: "What to forecast"
editor: 
  markdown: 
    wrap: sentence
---

## Targets file

The targets file is at 

```{r}
url <- "https://renc.osn.xsede.org/bio230121-bucket01/vera4cast/targets/duration=P1D/P1D-targets.csv.gz"
```

```{r message=FALSE}
library(tidyverse)
targets <- read_csv(url, show_col_types = FALSE)
```

```{r}
glimpse(targets)
```

### Variable list 

```{r message=FALSE}
googlesheets4::gs4_deauth()
target_metadata <- googlesheets4::read_sheet("https://docs.google.com/spreadsheets/d/1fOWo6zlcWA8F6PmRS9AD6n1pf-dTWSsmGKNpaX3yHNE/edit?usp=sharing")
```

```{r echo = FALSE}
  target_metadata <- target_metadata |> 
  rename(variable = `"official" targets name`) |> 
  select(variable, duration, class, `Variable name`, Description)
```

#### Physical variables

```{r echo = FALSE}
targets |> 
  distinct(variable, duration) |> 
  left_join(target_metadata, by = c("variable","duration")) |> 
  filter(class == "physical") |> 
  select(-class) |> 
  knitr::kable()
```
#### Chemical variables

```{r echo = FALSE}
targets |> 
  distinct(variable, duration) |> 
  left_join(target_metadata, by = c("variable","duration")) |> 
  filter(class == "chemical") |> 
  select(-class) |> 
  knitr::kable()
```

#### Biological variables

```{r echo = FALSE}
targets |> 
  distinct(variable, duration) |> 
  left_join(target_metadata, by = c("variable","duration")) |> 
  filter(class == "biological") |> 
  select(-class) |> 
  knitr::kable()
```

## Site
```{r}
site_list <- read_csv("https://raw.githubusercontent.com/LTREB-reservoirs/vera4cast/main/vera4cast_field_site_metadata.csv", show_col_types = FALSE)
```

```{r echo = FALSE}
site_list |> knitr::kable()
```
